//! The wgpu renderer: a 3D pass followed by a 2D HUD pass.
//!
//! **2D pipeline** (unchanged public API): instanced textured-quad rendering.
//! Every drawable—solid rects, sprites, and text glyphs—is a quad.
//!
//! **3D pipeline** (new, additive): vertex-color meshes with per-face normals
//! and directional + ambient lighting.  3D content is submitted via
//! [`Renderer::submit_mesh`] + [`Renderer::set_camera_3d`]; if nothing is
//! submitted the 3D pass clears then exits immediately so 2D games are
//! pixel-identical.
//!
//! Frame order: clear color + depth (3D pass) → load color, no depth (2D HUD pass).

use std::borrow::Cow;
use std::sync::Arc;

use wgpu::util::DeviceExt;
use winit::dpi::PhysicalSize;
use winit::window::Window;

use crate::font::GlyphAtlas;
use crate::math::{Rect, Vec2};
use crate::math3d::{CameraUniform, Vertex3D};
use crate::{Color, Texture};

/// MSAA sample count for the 3D pass.  4× is the minimum guaranteed by both
/// WebGL2 (GL_MAX_SAMPLES ≥ 4) and desktop OpenGL / Vulkan / Metal.
/// The 2D HUD pass stays at 1× (no MSAA needed for pixel-art quads).
const MSAA_SAMPLES: u32 = 4;

/// Built-in monospace font atlas (generated by tools/gen_assets.py).
const FONT_PNG: &[u8] = include_bytes!("../assets/font.png");
/// Font atlas layout: fixed cells, ASCII starting at `FONT_FIRST`.
pub(crate) const FONT_GLYPH_W: f32 = 18.0;
pub const FONT_GLYPH_H: f32 = 34.0;
pub(crate) const FONT_COLS: u32 = 16;
pub(crate) const FONT_ROWS: u32 = 6;
pub(crate) const FONT_FIRST: u32 = 32;

/// A single quad to draw: destination rect (pixels), optional source rect
/// (texels of `texture`; `None` = whole texture), texture, and tint.
#[derive(Clone, Copy)]
pub(crate) struct DrawItem {
    pub texture: Texture,
    pub dst: Rect,
    pub src: Option<Rect>,
    pub color: Color,
}

/// Per-quad instance data uploaded to the GPU.
#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct RectInstance {
    offset: [f32; 2],
    size: [f32; 2],
    uv_min: [f32; 2],
    uv_max: [f32; 2],
    color: [f32; 4],
}

/// Logical resolution uniform, padded to 16 bytes (std140-friendly).
#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct Resolution {
    size: [f32; 2],
    _pad: [f32; 2],
}

const QUAD_VERTICES: [[f32; 2]; 6] = [
    [0.0, 0.0],
    [1.0, 0.0],
    [1.0, 1.0],
    [0.0, 0.0],
    [1.0, 1.0],
    [0.0, 1.0],
];

const QUAD_ATTRS: [wgpu::VertexAttribute; 1] = wgpu::vertex_attr_array![0 => Float32x2];
const INSTANCE_ATTRS: [wgpu::VertexAttribute; 5] = wgpu::vertex_attr_array![
    1 => Float32x2, 2 => Float32x2, 3 => Float32x2, 4 => Float32x2, 5 => Float32x4
];

const INITIAL_INSTANCE_CAPACITY: u64 = 512;
/// Initial vertex/index buffer capacity for 3D meshes (in elements).
const INITIAL_3D_VERTEX_CAP: u64 = 4096;
const INITIAL_3D_INDEX_CAP: u64 = 8192;

/// A loaded texture, kept alive (with its view + sampler) by its bind group.
struct LoadedTexture {
    bind_group: wgpu::BindGroup,
    /// Raw texture view, kept so the 3D pipeline can create its own bind group
    /// using `texture_layout_3d` (which uses a different layout than the 2D pipeline).
    view: wgpu::TextureView,
    size: Vec2,
}

/// A single 3D draw call: range into the shared vertex/index buffers.
struct Mesh3D {
    vertex_offset: u32,
    index_offset: u32,
    index_count: u32,
}

/// Letterbox viewport: the axis-aligned rect inside the physical surface where
/// game content is rendered.  All four fields are in physical pixels.
#[derive(Clone, Copy)]
pub(crate) struct LetterboxViewport {
    pub x: u32,
    pub y: u32,
    pub w: u32,
    pub h: u32,
    /// Scale factor: how many physical pixels correspond to one logical pixel.
    pub scale: f32,
}

pub(crate) struct Renderer {
    _window: Arc<Window>,
    surface: wgpu::Surface<'static>,
    device: wgpu::Device,
    queue: wgpu::Queue,
    config: wgpu::SurfaceConfiguration,

    // ── 2D HUD pipeline ────────────────────────────────────────────────────
    pipeline: wgpu::RenderPipeline,
    quad_buffer: wgpu::Buffer,
    instance_buffer: wgpu::Buffer,
    instance_capacity: u64,
    _resolution_buffer: wgpu::Buffer,
    resolution_bind_group: wgpu::BindGroup,
    texture_layout: wgpu::BindGroupLayout,
    sampler: wgpu::Sampler,
    textures: Vec<LoadedTexture>,
    clear: Color,
    /// Scratch reused each frame to avoid per-frame allocation.
    instances: Vec<RectInstance>,

    /// The logical design resolution of the game (set once at startup).
    logical: Vec2,
    /// Computed letterbox viewport (physical pixels), updated on every resize.
    viewport: LetterboxViewport,

    // ── 3D pipeline ─────────────────────────────────────────────────────────
    pipeline_3d: wgpu::RenderPipeline,
    /// MSAA 4× multisampled color attachment for the 3D pass.
    /// Resolved to the swap-chain surface at the end of the 3D render pass.
    msaa_color_view: wgpu::TextureView,
    /// MSAA 4× depth texture matching the multisampled color attachment.
    msaa_depth_view: wgpu::TextureView,
    camera_buffer: wgpu::Buffer,
    camera_bind_group: wgpu::BindGroup,
    /// Bind group layout for group(1): texture + sampler used by 3D pipeline.
    texture_layout_3d: wgpu::BindGroupLayout,
    /// Sampler shared by the 3D texture bind group (NEAREST).
    sampler_3d: wgpu::Sampler,
    /// Bind group for the 1×1 white fallback (used when no texture is provided).
    white_bind_group_3d: wgpu::BindGroup,
    /// Combined vertex buffer for all 3D meshes this frame.
    vertex_buffer_3d: wgpu::Buffer,
    vertex_cap_3d: u64,
    /// Combined index buffer for all 3D meshes this frame.
    index_buffer_3d: wgpu::Buffer,
    index_cap_3d: u64,
    /// Accumulated 3D vertex data for the current frame.
    vertices_3d: Vec<Vertex3D>,
    /// Accumulated 3D index data for the current frame.
    indices_3d: Vec<u32>,
    /// Per-mesh draw descriptors collected during the frame.
    meshes_3d: Vec<Mesh3D>,
    /// Camera uniform for the current frame.
    camera_3d: CameraUniform,
    /// Texture handle to bind for the 3D pass this frame (None = white fallback).
    texture_3d: Option<Texture>,
    /// Sky/clear color override for the 3D pass this frame (None = use self.clear).
    sky_3d: Option<[f32; 4]>,

    // ── Glyph atlas (CJK text) ───────────────────────────────────────────────
    /// CPU-side glyph atlas shared across all Font instances.
    pub(crate) glyph_atlas: GlyphAtlas,
    /// GPU texture for the glyph atlas (RGBA8, grows dynamically).
    glyph_atlas_texture: wgpu::Texture,
    /// Bind group for `glyph_atlas_texture` (group(1), same layout as sprites).
    pub(crate) glyph_atlas_bind_group: wgpu::BindGroup,
    /// Texture handle that maps the glyph atlas into the `textures` vec (for DrawItem).
    pub(crate) glyph_atlas_handle: Texture,
}

impl Renderer {
    pub(crate) async fn new(window: Arc<Window>, clear: Color, logical: Vec2) -> Renderer {
        let raw = window.inner_size();
        // winit reports 0x0 for a freshly-attached web canvas; fall back to the
        // logical size so the surface isn't created at 1x1.
        let width = if raw.width == 0 {
            logical.x as u32
        } else {
            raw.width
        };
        let height = if raw.height == 0 {
            logical.y as u32
        } else {
            raw.height
        };

        let instance = wgpu::Instance::default();
        let surface = instance
            .create_surface(window.clone())
            .expect("failed to create surface");

        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::default(),
                force_fallback_adapter: false,
                compatible_surface: Some(&surface),
            })
            .await
            .expect("no compatible GPU adapter");

        let required_limits = if cfg!(target_arch = "wasm32") {
            wgpu::Limits::downlevel_webgl2_defaults()
        } else {
            wgpu::Limits::default()
        };

        let (device, queue) = adapter
            .request_device(&wgpu::DeviceDescriptor {
                label: Some("octiron device"),
                required_features: wgpu::Features::empty(),
                required_limits,
                ..Default::default()
            })
            .await
            .expect("failed to create device");

        let caps = surface.get_capabilities(&adapter);
        let format = *caps
            .formats
            .first()
            .expect("surface reports no supported formats");
        let config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format,
            width,
            height,
            present_mode: wgpu::PresentMode::Fifo,
            desired_maximum_frame_latency: 2,
            alpha_mode: caps
                .alpha_modes
                .first()
                .copied()
                .unwrap_or(wgpu::CompositeAlphaMode::Auto),
            view_formats: vec![],
        };
        surface.configure(&device, &config);

        log(&format!(
            "octiron init: backend={:?} surface={}x{} logical={}x{} format={:?}",
            adapter.get_info().backend,
            config.width,
            config.height,
            logical.x,
            logical.y,
            format,
        ));

        // ── 2D HUD shader + pipeline ─────────────────────────────────────────
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("octiron sprite shader"),
            source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(include_str!("sprite.wgsl"))),
        });

        // group(0): resolution uniform.
        let resolution_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("octiron resolution layout"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
            });

        // group(1): texture + sampler.
        let texture_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("octiron texture layout"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
            ],
        });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("octiron pipeline layout"),
            bind_group_layouts: &[Some(&resolution_layout), Some(&texture_layout)],
            ..Default::default()
        });

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("octiron pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                buffers: &[
                    wgpu::VertexBufferLayout {
                        array_stride: std::mem::size_of::<[f32; 2]>() as u64,
                        step_mode: wgpu::VertexStepMode::Vertex,
                        attributes: &QUAD_ATTRS,
                    },
                    wgpu::VertexBufferLayout {
                        array_stride: std::mem::size_of::<RectInstance>() as u64,
                        step_mode: wgpu::VertexStepMode::Instance,
                        attributes: &INSTANCE_ATTRS,
                    },
                ],
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                targets: &[Some(wgpu::ColorTargetState {
                    format: config.format,
                    blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
            }),
            primitive: wgpu::PrimitiveState::default(),
            depth_stencil: None,
            multisample: wgpu::MultisampleState::default(),
            multiview_mask: None,
            cache: None,
        });

        let quad_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("octiron quad"),
            contents: bytemuck::cast_slice(&QUAD_VERTICES),
            usage: wgpu::BufferUsages::VERTEX,
        });

        let instance_capacity = INITIAL_INSTANCE_CAPACITY;
        let instance_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("octiron instances"),
            size: instance_capacity * std::mem::size_of::<RectInstance>() as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let resolution = Resolution {
            size: [logical.x, logical.y],
            _pad: [0.0, 0.0],
        };
        let resolution_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("octiron resolution"),
            contents: bytemuck::bytes_of(&resolution),
            usage: wgpu::BufferUsages::UNIFORM,
        });
        let resolution_bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("octiron resolution bind group"),
            layout: &resolution_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: resolution_buffer.as_entire_binding(),
            }],
        });

        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("octiron sampler"),
            mag_filter: wgpu::FilterMode::Nearest,
            min_filter: wgpu::FilterMode::Nearest,
            mipmap_filter: wgpu::MipmapFilterMode::Nearest,
            ..Default::default()
        });

        // Built-in textures: 0 = white (solid fills/text base), 1 = font atlas.
        let white = create_texture(
            &device,
            &queue,
            &texture_layout,
            &sampler,
            "octiron white",
            1,
            1,
            &[255, 255, 255, 255],
        );
        let font_img = image::load_from_memory(FONT_PNG)
            .expect("decode font atlas")
            .to_rgba8();
        let (fw, fh) = font_img.dimensions();
        let font = create_texture(
            &device,
            &queue,
            &texture_layout,
            &sampler,
            "octiron font",
            fw,
            fh,
            &font_img.into_raw(),
        );

        // ── 3D pipeline ───────────────────────────────────────────────────────
        let shader_3d = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("octiron 3d shader"),
            source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(include_str!("3d.wgsl"))),
        });

        // group(0): CameraUniform.
        let camera_bind_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("octiron 3d camera layout"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
            });

        let camera_3d = CameraUniform::identity();
        let camera_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("octiron 3d camera"),
            contents: bytemuck::bytes_of(&camera_3d),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });
        let camera_bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("octiron 3d camera bind group"),
            layout: &camera_bind_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: camera_buffer.as_entire_binding(),
            }],
        });

        // group(1): texture + sampler for the 3D pass.
        let texture_layout_3d =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("octiron 3d texture layout"),
                entries: &[
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            sample_type: wgpu::TextureSampleType::Float { filterable: true },
                            view_dimension: wgpu::TextureViewDimension::D2,
                            multisampled: false,
                        },
                        count: None,
                    },
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                        count: None,
                    },
                ],
            });

        // Dedicated NEAREST sampler for 3D textures.
        let sampler_3d = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("octiron 3d sampler"),
            mag_filter: wgpu::FilterMode::Nearest,
            min_filter: wgpu::FilterMode::Nearest,
            mipmap_filter: wgpu::MipmapFilterMode::Nearest,
            ..Default::default()
        });

        // 1×1 white fallback texture for untextured 3D scenes.
        let white_3d_tex = {
            let size = wgpu::Extent3d { width: 1, height: 1, depth_or_array_layers: 1 };
            let tex = device.create_texture(&wgpu::TextureDescriptor {
                label: Some("octiron 3d white"),
                size,
                mip_level_count: 1,
                sample_count: 1,
                dimension: wgpu::TextureDimension::D2,
                format: wgpu::TextureFormat::Rgba8Unorm,
                usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
                view_formats: &[],
            });
            queue.write_texture(
                wgpu::TexelCopyTextureInfo {
                    texture: &tex,
                    mip_level: 0,
                    origin: wgpu::Origin3d::ZERO,
                    aspect: wgpu::TextureAspect::All,
                },
                &[255u8, 255, 255, 255],
                wgpu::TexelCopyBufferLayout {
                    offset: 0,
                    bytes_per_row: Some(4),
                    rows_per_image: Some(1),
                },
                size,
            );
            tex
        };
        let white_3d_view = white_3d_tex.create_view(&wgpu::TextureViewDescriptor::default());
        let white_bind_group_3d = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("octiron 3d white bind group"),
            layout: &texture_layout_3d,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::TextureView(&white_3d_view),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Sampler(&sampler_3d),
                },
            ],
        });

        let pipeline_layout_3d =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("octiron 3d pipeline layout"),
                bind_group_layouts: &[Some(&camera_bind_layout), Some(&texture_layout_3d)],
                ..Default::default()
            });

        let pipeline_3d = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("octiron 3d pipeline"),
            layout: Some(&pipeline_layout_3d),
            vertex: wgpu::VertexState {
                module: &shader_3d,
                entry_point: Some("vs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                buffers: &[Vertex3D::layout()],
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader_3d,
                entry_point: Some("fs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                targets: &[Some(wgpu::ColorTargetState {
                    format: config.format,
                    blend: Some(wgpu::BlendState::REPLACE),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
            }),
            primitive: wgpu::PrimitiveState {
                cull_mode: Some(wgpu::Face::Back),
                front_face: wgpu::FrontFace::Ccw,
                ..Default::default()
            },
            depth_stencil: Some(wgpu::DepthStencilState {
                format: wgpu::TextureFormat::Depth32Float,
                depth_write_enabled: Some(true),
                depth_compare: Some(wgpu::CompareFunction::Less),
                stencil: wgpu::StencilState::default(),
                bias: wgpu::DepthBiasState::default(),
            }),
            multisample: wgpu::MultisampleState {
                count: MSAA_SAMPLES,
                mask: !0,
                alpha_to_coverage_enabled: false,
            },
            multiview_mask: None,
            cache: None,
        });

        let msaa_color_view =
            create_msaa_color_texture(&device, config.format, config.width, config.height);
        let msaa_depth_view =
            create_depth_texture(&device, config.width, config.height, MSAA_SAMPLES);

        let vertex_cap_3d = INITIAL_3D_VERTEX_CAP;
        let vertex_buffer_3d = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("octiron 3d vertices"),
            size: vertex_cap_3d * std::mem::size_of::<Vertex3D>() as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let index_cap_3d = INITIAL_3D_INDEX_CAP;
        let index_buffer_3d = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("octiron 3d indices"),
            size: index_cap_3d * std::mem::size_of::<u32>() as u64,
            usage: wgpu::BufferUsages::INDEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let viewport = compute_viewport(width, height, logical.x, logical.y);

        // ── Glyph atlas (CJK text) ────────────────────────────────────────────
        // Slot index = 2 (0=white, 1=font, 2=glyph atlas).
        let glyph_atlas = GlyphAtlas::new();
        let (glyph_atlas_texture, glyph_atlas_bind_group) = create_glyph_atlas_texture(
            &device,
            &queue,
            &texture_layout,
            &sampler,
            glyph_atlas.dim,
            &glyph_atlas.pixels,
        );
        let glyph_atlas_view =
            glyph_atlas_texture.create_view(&wgpu::TextureViewDescriptor::default());
        let glyph_atlas_slot = LoadedTexture {
            bind_group: device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("octiron glyph atlas tex slot"),
                layout: &texture_layout,
                entries: &[
                    wgpu::BindGroupEntry {
                        binding: 0,
                        resource: wgpu::BindingResource::TextureView(&glyph_atlas_view),
                    },
                    wgpu::BindGroupEntry {
                        binding: 1,
                        resource: wgpu::BindingResource::Sampler(&sampler),
                    },
                ],
            }),
            view: glyph_atlas_view,
            size: Vec2::new(glyph_atlas.dim as f32, glyph_atlas.dim as f32),
        };
        let glyph_atlas_handle = Texture(2);

        Renderer {
            _window: window,
            surface,
            device,
            queue,
            config,
            pipeline,
            quad_buffer,
            instance_buffer,
            instance_capacity,
            _resolution_buffer: resolution_buffer,
            resolution_bind_group,
            texture_layout,
            sampler,
            textures: vec![white, font, glyph_atlas_slot],
            clear,
            instances: Vec::new(),
            logical,
            viewport,
            pipeline_3d,
            msaa_color_view,
            msaa_depth_view,
            camera_buffer,
            camera_bind_group,
            texture_layout_3d,
            sampler_3d,
            white_bind_group_3d,
            vertex_buffer_3d,
            vertex_cap_3d,
            index_buffer_3d,
            index_cap_3d,
            vertices_3d: Vec::new(),
            indices_3d: Vec::new(),
            meshes_3d: Vec::new(),
            camera_3d,
            texture_3d: None,
            sky_3d: None,
            glyph_atlas,
            glyph_atlas_texture,
            glyph_atlas_bind_group,
            glyph_atlas_handle,
        }
    }

    /// Decodes a PNG and uploads it as a new texture, returning its handle.
    pub(crate) fn load_texture(&mut self, bytes: &[u8]) -> Texture {
        let img = image::load_from_memory(bytes)
            .expect("failed to decode texture")
            .to_rgba8();
        let (w, h) = img.dimensions();
        let loaded = create_texture(
            &self.device,
            &self.queue,
            &self.texture_layout,
            &self.sampler,
            "octiron texture",
            w,
            h,
            &img.into_raw(),
        );
        let id = self.textures.len() as u32;
        self.textures.push(loaded);
        Texture(id)
    }

    pub(crate) fn texture_size(&self, texture: Texture) -> Vec2 {
        self.textures
            .get(texture.0 as usize)
            .map(|t| t.size)
            .unwrap_or(Vec2::new(1.0, 1.0))
    }

    pub(crate) fn resize(&mut self, new_size: PhysicalSize<u32>) {
        if new_size.width == 0 || new_size.height == 0 {
            return;
        }
        self.config.width = new_size.width;
        self.config.height = new_size.height;
        self.surface.configure(&self.device, &self.config);
        // Recreate MSAA textures — WebGL2 textures are immutable once created,
        // so we must create new ones at the new size.
        self.msaa_color_view = create_msaa_color_texture(
            &self.device,
            self.config.format,
            new_size.width,
            new_size.height,
        );
        self.msaa_depth_view =
            create_depth_texture(&self.device, new_size.width, new_size.height, MSAA_SAMPLES);
        // Recompute letterbox viewport for the new surface size.
        self.viewport = compute_viewport(
            new_size.width,
            new_size.height,
            self.logical.x,
            self.logical.y,
        );
    }

    /// Current letterbox viewport (physical pixels).
    pub(crate) fn letterbox_viewport(&self) -> LetterboxViewport {
        self.viewport
    }

    // ── 3D submission API ─────────────────────────────────────────────────────

    /// Queues a 3D mesh for this frame.
    ///
    /// `vertices` and `indices` are appended into shared per-frame buffers.
    /// A model matrix can be baked into vertex positions by the caller before
    /// submitting (or the caller can submit pre-transformed geometry).
    pub(crate) fn submit_mesh(&mut self, vertices: &[Vertex3D], indices: &[u32]) {
        let vertex_offset = self.vertices_3d.len() as u32;
        let index_offset = self.indices_3d.len() as u32;
        self.vertices_3d.extend_from_slice(vertices);
        self.indices_3d.extend_from_slice(indices);
        self.meshes_3d.push(Mesh3D {
            vertex_offset,
            index_offset,
            index_count: indices.len() as u32,
        });
    }

    /// Sets the camera/lighting uniform for this frame's 3D pass.
    pub(crate) fn set_camera_3d(&mut self, camera: CameraUniform) {
        self.camera_3d = camera;
    }

    /// Sets an optional texture to sample in the 3D pass for this frame.
    ///
    /// `None` (default) falls back to the 1×1 white texture so untextured meshes
    /// are rendered with pure vertex-color × lighting, identical to the old pipeline.
    pub(crate) fn set_texture_3d(&mut self, texture: Option<Texture>) {
        self.texture_3d = texture;
    }

    /// Overrides the sky/clear color for the 3D pass this frame.
    ///
    /// `None` (default) clears to the `Config::clear_color` set at startup,
    /// preserving the existing behaviour for all games that do not supply a sky.
    pub(crate) fn set_sky_3d(&mut self, sky: Option<[f32; 4]>) {
        self.sky_3d = sky;
    }

    /// Builds a wgpu bind group for the given 3D texture handle using the
    /// `texture_layout_3d` (group 1 of the 3D pipeline).
    ///
    /// The returned bind group is valid for the current frame's 3D pass.
    pub(crate) fn make_texture_bind_group_3d(&self, texture: Texture) -> wgpu::BindGroup {
        let loaded = &self.textures[texture.0 as usize];
        self.device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("octiron 3d user texture bind group"),
            layout: &self.texture_layout_3d,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::TextureView(&loaded.view),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Sampler(&self.sampler_3d),
                },
            ],
        })
    }

    // ── Render ────────────────────────────────────────────────────────────────

    /// Uploads the glyph atlas to the GPU if it has been modified.
    ///
    /// Called automatically at the start of each `render` call.  If the atlas
    /// dimensions have changed (growth), the old texture is dropped and a new
    /// one is allocated, and the corresponding slot in `self.textures` is updated.
    pub(crate) fn flush_glyph_atlas(&mut self) {
        if !self.glyph_atlas.dirty {
            return;
        }
        let dim = self.glyph_atlas.dim;
        let cur_dim = self.textures[self.glyph_atlas_handle.0 as usize].size.x as u32;

        if dim != cur_dim {
            // Texture grew: allocate a new GPU texture and replace the slot.
            let (new_tex, new_bg) = create_glyph_atlas_texture(
                &self.device,
                &self.queue,
                &self.texture_layout,
                &self.sampler,
                dim,
                &self.glyph_atlas.pixels,
            );
            let new_view = new_tex.create_view(&wgpu::TextureViewDescriptor::default());
            self.textures[self.glyph_atlas_handle.0 as usize] = LoadedTexture {
                bind_group: self.device.create_bind_group(&wgpu::BindGroupDescriptor {
                    label: Some("octiron glyph atlas tex slot"),
                    layout: &self.texture_layout,
                    entries: &[
                        wgpu::BindGroupEntry {
                            binding: 0,
                            resource: wgpu::BindingResource::TextureView(&new_view),
                        },
                        wgpu::BindGroupEntry {
                            binding: 1,
                            resource: wgpu::BindingResource::Sampler(&self.sampler),
                        },
                    ],
                }),
                view: new_view,
                size: Vec2::new(dim as f32, dim as f32),
            };
            self.glyph_atlas_bind_group = new_bg;
            self.glyph_atlas_texture = new_tex;
        } else {
            // Same size: write-update the existing texture.
            let size = wgpu::Extent3d {
                width: dim,
                height: dim,
                depth_or_array_layers: 1,
            };
            self.queue.write_texture(
                wgpu::TexelCopyTextureInfo {
                    texture: &self.glyph_atlas_texture,
                    mip_level: 0,
                    origin: wgpu::Origin3d::ZERO,
                    aspect: wgpu::TextureAspect::All,
                },
                &self.glyph_atlas.pixels,
                wgpu::TexelCopyBufferLayout {
                    offset: 0,
                    bytes_per_row: Some(4 * dim),
                    rows_per_image: Some(dim),
                },
                size,
            );
        }
        self.glyph_atlas.dirty = false;
    }

    pub(crate) fn render(&mut self, items: &[DrawItem]) {
        // ── Flush glyph atlas to GPU if dirty ─────────────────────────────────
        self.flush_glyph_atlas();

        // ── Build 2D instances ────────────────────────────────────────────────
        self.instances.clear();
        self.instances.reserve(items.len());
        for item in items {
            let tex_size = self.texture_size(item.texture);
            let (uv_min, uv_max) = match item.src {
                Some(src) => (
                    [src.x / tex_size.x, src.y / tex_size.y],
                    [(src.x + src.w) / tex_size.x, (src.y + src.h) / tex_size.y],
                ),
                None => ([0.0, 0.0], [1.0, 1.0]),
            };
            self.instances.push(RectInstance {
                offset: [item.dst.x, item.dst.y],
                size: [item.dst.w, item.dst.h],
                uv_min,
                uv_max,
                color: item.color,
            });
        }
        self.ensure_instance_capacity(self.instances.len() as u64);
        if !self.instances.is_empty() {
            self.queue.write_buffer(
                &self.instance_buffer,
                0,
                bytemuck::cast_slice(&self.instances),
            );
        }

        // ── Upload 3D geometry ───────────────────────────────────────────────
        let has_3d = !self.meshes_3d.is_empty();
        if has_3d {
            self.ensure_3d_vertex_capacity(self.vertices_3d.len() as u64);
            self.ensure_3d_index_capacity(self.indices_3d.len() as u64);
            self.queue.write_buffer(
                &self.vertex_buffer_3d,
                0,
                bytemuck::cast_slice(&self.vertices_3d),
            );
            self.queue.write_buffer(
                &self.index_buffer_3d,
                0,
                bytemuck::cast_slice(&self.indices_3d),
            );
            self.queue.write_buffer(
                &self.camera_buffer,
                0,
                bytemuck::bytes_of(&self.camera_3d),
            );
        }

        // ── Acquire frame ─────────────────────────────────────────────────────
        let frame = match self.surface.get_current_texture() {
            wgpu::CurrentSurfaceTexture::Success(f)
            | wgpu::CurrentSurfaceTexture::Suboptimal(f) => f,
            wgpu::CurrentSurfaceTexture::Outdated | wgpu::CurrentSurfaceTexture::Lost => {
                self.surface.configure(&self.device, &self.config);
                // Clear 3D state so the next frame starts fresh.
                self.meshes_3d.clear();
                self.vertices_3d.clear();
                self.indices_3d.clear();
                self.texture_3d = None;
                self.sky_3d = None;
                return;
            }
            _ => return,
        };
        let view = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("octiron encoder"),
            });

        // ── 3D pass (MSAA 4×): render into multisampled color+depth, resolve to surface ──
        {
            // Clear the entire surface to the game's background color.  Letterbox
            // bars (outside the viewport) will therefore show the same background
            // color rather than black, which is acceptable and keeps the 2D games
            // (platformer sky-blue, survivor dark-green) visually correct.
            let sky_color = self.sky_3d.unwrap_or(self.clear);
            let vp = self.viewport;
            let mut pass_3d = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("octiron 3d pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    // Draw into the 4× MSAA texture …
                    view: &self.msaa_color_view,
                    // … and resolve to the swap-chain surface automatically.
                    resolve_target: Some(&view),
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: sky_color[0] as f64,
                            g: sky_color[1] as f64,
                            b: sky_color[2] as f64,
                            a: sky_color[3] as f64,
                        }),
                        // MSAA attachments must use Discard (contents are
                        // temporary; the resolved surface is what's kept).
                        store: wgpu::StoreOp::Discard,
                    },
                    depth_slice: None,
                })],
                depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                    view: &self.msaa_depth_view,
                    depth_ops: Some(wgpu::Operations {
                        load: wgpu::LoadOp::Clear(1.0),
                        store: wgpu::StoreOp::Discard,
                    }),
                    stencil_ops: None,
                }),
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });

            // Apply letterbox viewport so 3D content is confined to the game rect.
            pass_3d.set_viewport(
                vp.x as f32,
                vp.y as f32,
                vp.w as f32,
                vp.h as f32,
                0.0,
                1.0,
            );

            if has_3d {
                // Build the 3D texture bind group for group(1).
                // We build it here (before the render pass borrows self mutably)
                // so we can pass a reference into the pass.
                let user_tex_bg: Option<wgpu::BindGroup> =
                    self.texture_3d.map(|t| self.make_texture_bind_group_3d(t));
                let tex_bind_group: &wgpu::BindGroup = user_tex_bg
                    .as_ref()
                    .unwrap_or(&self.white_bind_group_3d);

                pass_3d.set_pipeline(&self.pipeline_3d);
                pass_3d.set_bind_group(0, &self.camera_bind_group, &[]);
                pass_3d.set_bind_group(1, tex_bind_group, &[]);
                pass_3d.set_vertex_buffer(0, self.vertex_buffer_3d.slice(..));
                pass_3d.set_index_buffer(
                    self.index_buffer_3d.slice(..),
                    wgpu::IndexFormat::Uint32,
                );
                for mesh in &self.meshes_3d {
                    let idx_range =
                        mesh.index_offset..mesh.index_offset + mesh.index_count;
                    pass_3d.draw_indexed(idx_range, mesh.vertex_offset as i32, 0..1);
                }
            }
        } // end 3D pass

        // ── 2D HUD pass: Load color (preserve 3D black bars), no depth ────────
        {
            let vp = self.viewport;
            let mut pass_2d = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("octiron 2d hud pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Load,
                        store: wgpu::StoreOp::Store,
                    },
                    depth_slice: None,
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });

            // Apply letterbox viewport: 2D quads are drawn in logical-pixel
            // coordinates (via the resolution uniform); the viewport transform
            // maps them to the physical letterbox rect on screen.
            pass_2d.set_viewport(
                vp.x as f32,
                vp.y as f32,
                vp.w as f32,
                vp.h as f32,
                0.0,
                1.0,
            );

            if !items.is_empty() {
                pass_2d.set_pipeline(&self.pipeline);
                pass_2d.set_bind_group(0, &self.resolution_bind_group, &[]);
                pass_2d.set_vertex_buffer(0, self.quad_buffer.slice(..));
                pass_2d.set_vertex_buffer(1, self.instance_buffer.slice(..));

                // Draw runs of consecutive same-texture items as one call each.
                let mut start = 0usize;
                while start < items.len() {
                    let tex = items[start].texture;
                    let mut end = start + 1;
                    while end < items.len() && items[end].texture == tex {
                        end += 1;
                    }
                    if let Some(loaded) = self.textures.get(tex.0 as usize) {
                        pass_2d.set_bind_group(1, &loaded.bind_group, &[]);
                        pass_2d.draw(0..6, start as u32..end as u32);
                    }
                    start = end;
                }
            }
        } // end 2D HUD pass

        self.queue.submit(std::iter::once(encoder.finish()));
        frame.present();

        // Reset per-frame 3D state.
        self.meshes_3d.clear();
        self.vertices_3d.clear();
        self.indices_3d.clear();
        self.texture_3d = None;
        self.sky_3d = None;
    }

    fn ensure_instance_capacity(&mut self, count: u64) {
        if count <= self.instance_capacity {
            return;
        }
        let mut cap = self.instance_capacity.max(1);
        while cap < count {
            cap = cap.saturating_mul(2);
        }
        self.instance_capacity = cap;
        self.instance_buffer = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("octiron instances"),
            size: cap * std::mem::size_of::<RectInstance>() as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
    }

    fn ensure_3d_vertex_capacity(&mut self, count: u64) {
        if count <= self.vertex_cap_3d {
            return;
        }
        let mut cap = self.vertex_cap_3d.max(1);
        while cap < count {
            cap = cap.saturating_mul(2);
        }
        self.vertex_cap_3d = cap;
        self.vertex_buffer_3d = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("octiron 3d vertices"),
            size: cap * std::mem::size_of::<Vertex3D>() as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
    }

    fn ensure_3d_index_capacity(&mut self, count: u64) {
        if count <= self.index_cap_3d {
            return;
        }
        let mut cap = self.index_cap_3d.max(1);
        while cap < count {
            cap = cap.saturating_mul(2);
        }
        self.index_cap_3d = cap;
        self.index_buffer_3d = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("octiron 3d indices"),
            size: cap * std::mem::size_of::<u32>() as u64,
            usage: wgpu::BufferUsages::INDEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
    }
}

// ── Helper functions ─────────────────────────────────────────────────────────

/// Computes a uniform-scale, centred letterbox viewport given the physical
/// surface dimensions and the game's logical design resolution.
fn compute_viewport(sw: u32, sh: u32, lw: f32, lh: f32) -> LetterboxViewport {
    let scale_x = sw as f32 / lw;
    let scale_y = sh as f32 / lh;
    let scale = scale_x.min(scale_y);
    let w = (lw * scale).round() as u32;
    let h = (lh * scale).round() as u32;
    let x = (sw.saturating_sub(w)) / 2;
    let y = (sh.saturating_sub(h)) / 2;
    LetterboxViewport { x, y, w, h, scale }
}

/// Creates a multisampled color texture for the 3D MSAA pass and returns its view.
///
/// The texture uses the same format as the swap-chain surface so that wgpu can
/// resolve it into the surface automatically via `resolve_target`.
fn create_msaa_color_texture(
    device: &wgpu::Device,
    format: wgpu::TextureFormat,
    width: u32,
    height: u32,
) -> wgpu::TextureView {
    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("octiron msaa color texture"),
        size: wgpu::Extent3d { width, height, depth_or_array_layers: 1 },
        mip_level_count: 1,
        sample_count: MSAA_SAMPLES,
        dimension: wgpu::TextureDimension::D2,
        format,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
        view_formats: &[],
    });
    texture.create_view(&wgpu::TextureViewDescriptor::default())
}

/// Creates a Depth32Float texture and returns its view.
///
/// `sample_count` should be 1 for a plain depth texture or `MSAA_SAMPLES` for
/// the multisampled depth attachment of the 3D MSAA pass.
fn create_depth_texture(
    device: &wgpu::Device,
    width: u32,
    height: u32,
    sample_count: u32,
) -> wgpu::TextureView {
    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("octiron depth texture"),
        size: wgpu::Extent3d {
            width,
            height,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Depth32Float,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
        view_formats: &[],
    });
    texture.create_view(&wgpu::TextureViewDescriptor::default())
}

fn create_texture(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    layout: &wgpu::BindGroupLayout,
    sampler: &wgpu::Sampler,
    label: &str,
    width: u32,
    height: u32,
    rgba: &[u8],
) -> LoadedTexture {
    let size = wgpu::Extent3d {
        width,
        height,
        depth_or_array_layers: 1,
    };
    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some(label),
        size,
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    queue.write_texture(
        wgpu::TexelCopyTextureInfo {
            texture: &texture,
            mip_level: 0,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        rgba,
        wgpu::TexelCopyBufferLayout {
            offset: 0,
            bytes_per_row: Some(4 * width),
            rows_per_image: Some(height),
        },
        size,
    );
    let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
    let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some(label),
        layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&view),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: wgpu::BindingResource::Sampler(sampler),
            },
        ],
    });
    LoadedTexture {
        bind_group,
        view,
        size: Vec2::new(width as f32, height as f32),
    }
}

/// Creates a fresh `Rgba8Unorm` GPU texture for the glyph atlas and a bind group
/// for the 2D sprite pipeline (group 1: texture + sampler).
fn create_glyph_atlas_texture(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    layout: &wgpu::BindGroupLayout,
    sampler: &wgpu::Sampler,
    dim: u32,
    pixels: &[u8],
) -> (wgpu::Texture, wgpu::BindGroup) {
    let size = wgpu::Extent3d { width: dim, height: dim, depth_or_array_layers: 1 };
    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("octiron glyph atlas"),
        size,
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    queue.write_texture(
        wgpu::TexelCopyTextureInfo {
            texture: &texture,
            mip_level: 0,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        pixels,
        wgpu::TexelCopyBufferLayout {
            offset: 0,
            bytes_per_row: Some(4 * dim),
            rows_per_image: Some(dim),
        },
        size,
    );
    let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
    let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("octiron glyph atlas bind group"),
        layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&view),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: wgpu::BindingResource::Sampler(sampler),
            },
        ],
    });
    (texture, bind_group)
}

fn log(message: &str) {
    #[cfg(target_arch = "wasm32")]
    web_sys::console::log_1(&wasm_bindgen::JsValue::from_str(message));
    #[cfg(not(target_arch = "wasm32"))]
    log::info!("{message}");
}
