//! The wgpu renderer: a single instanced, textured-quad pipeline.
//!
//! Every drawable—solid rects, sprites, and text glyphs—is a quad with a
//! source UV rect, a texture, and a tint color. Untextured fills use a built-in
//! 1x1 white texture (so one pipeline handles everything); text uses a built-in
//! monospace font atlas. Draw items are submitted in order and batched into one
//! draw call per run of consecutive same-texture items, preserving layering.
//!
//! Coordinates are a fixed *logical* resolution stretched to fill the canvas,
//! independent of device pixel ratio.

use std::borrow::Cow;
use std::sync::Arc;

use wgpu::util::DeviceExt;
use winit::dpi::PhysicalSize;
use winit::window::Window;

use crate::math::{Rect, Vec2};
use crate::{Color, Texture};

/// Built-in monospace font atlas (generated by tools/gen_assets.py).
const FONT_PNG: &[u8] = include_bytes!("../assets/font.png");
/// Font atlas layout: fixed cells, ASCII starting at `FONT_FIRST`.
pub(crate) const FONT_GLYPH_W: f32 = 18.0;
pub(crate) const FONT_GLYPH_H: f32 = 34.0;
pub(crate) const FONT_COLS: u32 = 16;
pub(crate) const FONT_ROWS: u32 = 6;
pub(crate) const FONT_FIRST: u32 = 32;

/// A single quad to draw: destination rect (pixels), optional source rect
/// (texels of `texture`; `None` = whole texture), texture, and tint.
#[derive(Clone, Copy)]
pub(crate) struct DrawItem {
    pub texture: Texture,
    pub dst: Rect,
    pub src: Option<Rect>,
    pub color: Color,
}

/// Per-quad instance data uploaded to the GPU.
#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct RectInstance {
    offset: [f32; 2],
    size: [f32; 2],
    uv_min: [f32; 2],
    uv_max: [f32; 2],
    color: [f32; 4],
}

/// Logical resolution uniform, padded to 16 bytes (std140-friendly).
#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct Resolution {
    size: [f32; 2],
    _pad: [f32; 2],
}

const QUAD_VERTICES: [[f32; 2]; 6] = [
    [0.0, 0.0],
    [1.0, 0.0],
    [1.0, 1.0],
    [0.0, 0.0],
    [1.0, 1.0],
    [0.0, 1.0],
];

const QUAD_ATTRS: [wgpu::VertexAttribute; 1] = wgpu::vertex_attr_array![0 => Float32x2];
const INSTANCE_ATTRS: [wgpu::VertexAttribute; 5] = wgpu::vertex_attr_array![
    1 => Float32x2, 2 => Float32x2, 3 => Float32x2, 4 => Float32x2, 5 => Float32x4
];

const INITIAL_INSTANCE_CAPACITY: u64 = 512;

/// A loaded texture, kept alive (with its view + sampler) by its bind group.
struct LoadedTexture {
    bind_group: wgpu::BindGroup,
    size: Vec2,
}

pub(crate) struct Renderer {
    _window: Arc<Window>,
    surface: wgpu::Surface<'static>,
    device: wgpu::Device,
    queue: wgpu::Queue,
    config: wgpu::SurfaceConfiguration,
    pipeline: wgpu::RenderPipeline,
    quad_buffer: wgpu::Buffer,
    instance_buffer: wgpu::Buffer,
    instance_capacity: u64,
    _resolution_buffer: wgpu::Buffer,
    resolution_bind_group: wgpu::BindGroup,
    texture_layout: wgpu::BindGroupLayout,
    sampler: wgpu::Sampler,
    textures: Vec<LoadedTexture>,
    clear: Color,
    // Scratch reused each frame to avoid per-frame allocation.
    instances: Vec<RectInstance>,
}

impl Renderer {
    pub(crate) async fn new(window: Arc<Window>, clear: Color, logical: Vec2) -> Renderer {
        let raw = window.inner_size();
        // winit reports 0x0 for a freshly-attached web canvas; fall back to the
        // logical size so the surface isn't created at 1x1.
        let width = if raw.width == 0 {
            logical.x as u32
        } else {
            raw.width
        };
        let height = if raw.height == 0 {
            logical.y as u32
        } else {
            raw.height
        };

        let instance = wgpu::Instance::default();
        let surface = instance
            .create_surface(window.clone())
            .expect("failed to create surface");

        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::default(),
                force_fallback_adapter: false,
                compatible_surface: Some(&surface),
            })
            .await
            .expect("no compatible GPU adapter");

        let required_limits = if cfg!(target_arch = "wasm32") {
            wgpu::Limits::downlevel_webgl2_defaults()
        } else {
            wgpu::Limits::default()
        };

        let (device, queue) = adapter
            .request_device(&wgpu::DeviceDescriptor {
                label: Some("octiron device"),
                required_features: wgpu::Features::empty(),
                required_limits,
                ..Default::default()
            })
            .await
            .expect("failed to create device");

        let caps = surface.get_capabilities(&adapter);
        let format = *caps
            .formats
            .first()
            .expect("surface reports no supported formats");
        let config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format,
            width,
            height,
            present_mode: wgpu::PresentMode::Fifo,
            desired_maximum_frame_latency: 2,
            alpha_mode: caps
                .alpha_modes
                .first()
                .copied()
                .unwrap_or(wgpu::CompositeAlphaMode::Auto),
            view_formats: vec![],
        };
        surface.configure(&device, &config);

        log(&format!(
            "octiron init: backend={:?} surface={}x{} logical={}x{} format={:?}",
            adapter.get_info().backend,
            config.width,
            config.height,
            logical.x,
            logical.y,
            format,
        ));

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("octiron sprite shader"),
            source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(include_str!("sprite.wgsl"))),
        });

        // group(0): resolution uniform.
        let resolution_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("octiron resolution layout"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
            });

        // group(1): texture + sampler.
        let texture_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("octiron texture layout"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
            ],
        });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("octiron pipeline layout"),
            bind_group_layouts: &[Some(&resolution_layout), Some(&texture_layout)],
            ..Default::default()
        });

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("octiron pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                buffers: &[
                    wgpu::VertexBufferLayout {
                        array_stride: std::mem::size_of::<[f32; 2]>() as u64,
                        step_mode: wgpu::VertexStepMode::Vertex,
                        attributes: &QUAD_ATTRS,
                    },
                    wgpu::VertexBufferLayout {
                        array_stride: std::mem::size_of::<RectInstance>() as u64,
                        step_mode: wgpu::VertexStepMode::Instance,
                        attributes: &INSTANCE_ATTRS,
                    },
                ],
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                targets: &[Some(wgpu::ColorTargetState {
                    format: config.format,
                    blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
            }),
            primitive: wgpu::PrimitiveState::default(),
            depth_stencil: None,
            multisample: wgpu::MultisampleState::default(),
            multiview_mask: None,
            cache: None,
        });

        let quad_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("octiron quad"),
            contents: bytemuck::cast_slice(&QUAD_VERTICES),
            usage: wgpu::BufferUsages::VERTEX,
        });

        let instance_capacity = INITIAL_INSTANCE_CAPACITY;
        let instance_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("octiron instances"),
            size: instance_capacity * std::mem::size_of::<RectInstance>() as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let resolution = Resolution {
            size: [logical.x, logical.y],
            _pad: [0.0, 0.0],
        };
        let resolution_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("octiron resolution"),
            contents: bytemuck::bytes_of(&resolution),
            usage: wgpu::BufferUsages::UNIFORM,
        });
        let resolution_bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("octiron resolution bind group"),
            layout: &resolution_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: resolution_buffer.as_entire_binding(),
            }],
        });

        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("octiron sampler"),
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::MipmapFilterMode::Nearest,
            ..Default::default()
        });

        // Built-in textures: 0 = white (solid fills/text base), 1 = font atlas.
        let white = create_texture(
            &device,
            &queue,
            &texture_layout,
            &sampler,
            "octiron white",
            1,
            1,
            &[255, 255, 255, 255],
        );
        let font_img = image::load_from_memory(FONT_PNG)
            .expect("decode font atlas")
            .to_rgba8();
        let (fw, fh) = font_img.dimensions();
        let font = create_texture(
            &device,
            &queue,
            &texture_layout,
            &sampler,
            "octiron font",
            fw,
            fh,
            &font_img.into_raw(),
        );

        Renderer {
            _window: window,
            surface,
            device,
            queue,
            config,
            pipeline,
            quad_buffer,
            instance_buffer,
            instance_capacity,
            _resolution_buffer: resolution_buffer,
            resolution_bind_group,
            texture_layout,
            sampler,
            textures: vec![white, font],
            clear,
            instances: Vec::new(),
        }
    }

    /// Decodes a PNG and uploads it as a new texture, returning its handle.
    pub(crate) fn load_texture(&mut self, bytes: &[u8]) -> Texture {
        let img = image::load_from_memory(bytes)
            .expect("failed to decode texture")
            .to_rgba8();
        let (w, h) = img.dimensions();
        let loaded = create_texture(
            &self.device,
            &self.queue,
            &self.texture_layout,
            &self.sampler,
            "octiron texture",
            w,
            h,
            &img.into_raw(),
        );
        let id = self.textures.len() as u32;
        self.textures.push(loaded);
        Texture(id)
    }

    pub(crate) fn texture_size(&self, texture: Texture) -> Vec2 {
        self.textures
            .get(texture.0 as usize)
            .map(|t| t.size)
            .unwrap_or(Vec2::new(1.0, 1.0))
    }

    pub(crate) fn resize(&mut self, new_size: PhysicalSize<u32>) {
        if new_size.width == 0 || new_size.height == 0 {
            return;
        }
        self.config.width = new_size.width;
        self.config.height = new_size.height;
        self.surface.configure(&self.device, &self.config);
    }

    pub(crate) fn render(&mut self, items: &[DrawItem]) {
        // Build instances (converting source texels to UVs per texture).
        self.instances.clear();
        self.instances.reserve(items.len());
        for item in items {
            let tex_size = self.texture_size(item.texture);
            let (uv_min, uv_max) = match item.src {
                Some(src) => (
                    [src.x / tex_size.x, src.y / tex_size.y],
                    [(src.x + src.w) / tex_size.x, (src.y + src.h) / tex_size.y],
                ),
                None => ([0.0, 0.0], [1.0, 1.0]),
            };
            self.instances.push(RectInstance {
                offset: [item.dst.x, item.dst.y],
                size: [item.dst.w, item.dst.h],
                uv_min,
                uv_max,
                color: item.color,
            });
        }

        self.ensure_instance_capacity(self.instances.len() as u64);
        if !self.instances.is_empty() {
            self.queue.write_buffer(
                &self.instance_buffer,
                0,
                bytemuck::cast_slice(&self.instances),
            );
        }

        let frame = match self.surface.get_current_texture() {
            wgpu::CurrentSurfaceTexture::Success(frame)
            | wgpu::CurrentSurfaceTexture::Suboptimal(frame) => frame,
            wgpu::CurrentSurfaceTexture::Outdated | wgpu::CurrentSurfaceTexture::Lost => {
                self.surface.configure(&self.device, &self.config);
                return;
            }
            _ => return,
        };
        let view = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("octiron encoder"),
            });
        {
            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("octiron pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: self.clear[0] as f64,
                            g: self.clear[1] as f64,
                            b: self.clear[2] as f64,
                            a: self.clear[3] as f64,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                    depth_slice: None,
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });

            if !items.is_empty() {
                pass.set_pipeline(&self.pipeline);
                pass.set_bind_group(0, &self.resolution_bind_group, &[]);
                pass.set_vertex_buffer(0, self.quad_buffer.slice(..));
                pass.set_vertex_buffer(1, self.instance_buffer.slice(..));

                // Draw runs of consecutive same-texture items as one call each.
                let mut start = 0usize;
                while start < items.len() {
                    let tex = items[start].texture;
                    let mut end = start + 1;
                    while end < items.len() && items[end].texture == tex {
                        end += 1;
                    }
                    if let Some(loaded) = self.textures.get(tex.0 as usize) {
                        pass.set_bind_group(1, &loaded.bind_group, &[]);
                        pass.draw(0..6, start as u32..end as u32);
                    }
                    start = end;
                }
            }
        }

        self.queue.submit(std::iter::once(encoder.finish()));
        frame.present();
    }

    fn ensure_instance_capacity(&mut self, count: u64) {
        if count <= self.instance_capacity {
            return;
        }
        let mut cap = self.instance_capacity.max(1);
        while cap < count {
            cap = cap.saturating_mul(2);
        }
        self.instance_capacity = cap;
        self.instance_buffer = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("octiron instances"),
            size: cap * std::mem::size_of::<RectInstance>() as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
    }
}

fn create_texture(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    layout: &wgpu::BindGroupLayout,
    sampler: &wgpu::Sampler,
    label: &str,
    width: u32,
    height: u32,
    rgba: &[u8],
) -> LoadedTexture {
    let size = wgpu::Extent3d {
        width,
        height,
        depth_or_array_layers: 1,
    };
    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some(label),
        size,
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    queue.write_texture(
        wgpu::TexelCopyTextureInfo {
            texture: &texture,
            mip_level: 0,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        rgba,
        wgpu::TexelCopyBufferLayout {
            offset: 0,
            bytes_per_row: Some(4 * width),
            rows_per_image: Some(height),
        },
        size,
    );
    let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
    let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some(label),
        layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&view),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: wgpu::BindingResource::Sampler(sampler),
            },
        ],
    });
    LoadedTexture {
        bind_group,
        size: Vec2::new(width as f32, height as f32),
    }
}

fn log(message: &str) {
    #[cfg(target_arch = "wasm32")]
    web_sys::console::log_1(&wasm_bindgen::JsValue::from_str(message));
    #[cfg(not(target_arch = "wasm32"))]
    log::info!("{message}");
}
